### ISSUE TITLE
Can you show some experiment results?

### ISSUE THREAD

**Issue by wodaka** [Mohammadreza-Beygifard/cifar10_pytorch#6]
How accurate is the model?

**Comment by Mohammadreza-Beygifard** [comment]
On the test set, the dataset that the model has never visited 82.33%
I will push this model state soon!

<img width="431" alt="Screenshot 2023-11-19 at 21 48 51" src="https://github.com/Mohammadreza-Beygifard/cifar10_pytorch/assets/61592071/39a1d8ef-395b-474e-825d-527e5dc90581">

**Comment by wodaka** [comment]
okok, Thanks.
